### ISSUE TITLE
Make Kirby 3 default branch

### ISSUE THREAD

**Issue by distantnative** [jbeyerstedt/kirby-kirbytag-download#3]
Would be my suggestion and keeping the v2 version saved in a separate branch.

**Comment by jbeyerstedt** [comment]
Thanks for the trigger to actually do it. Currently I don't have much time to maintain my plugins because of my master's thesis.
I think the best solution will be to just change the default branch and keep the `master` branch for the Kirby 2 version. Because renaming the "old" branch will break existing repositories (e.g. when using submodules).
Names are just names in the end and I added some words about the fact, that the `master` branch is not the latest development any more in the readme.
